### ISSUE TITLE
Extend Snapshot/Restore support for non-AWS but S3-compatible API

### ISSUE THREAD

**Issue by imotov** [elasticsearch/elasticsearch-cloud-aws#158]
Moved from https://github.com/elasticsearch/elasticsearch/issues/5839

**Comment by tlrx** [comment]
@ppat since https://github.com/elasticsearch/elasticsearch-cloud-aws/issues/147 you can specify specific and non-AWS S3 repository endpoints. I think it should do the job, what do you think?

**Comment by ppat** [comment]
That looks like it might work but I have moved on since I created this ticket originally.

**Comment by tlrx** [comment]
@ppat ok, thanks. I close this issue, feel free to reopen it if necessary.
