### ISSUE TITLE
Incorrect plugin install command in the README

### ISSUE THREAD

**Issue by anandchida** [elasticsearch/elasticsearch-cloud-aws#164]
The plugin install command mentioned in the README doc is 

bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.4.1

which fails with error 
Error while installing plugin, reason: ElasticsearchIllegalArgumentException: Illegal plugin name: elasticsearch

the correct command should be 

bin/plugin -install elasticsearch/cloud-aws/2.­4.1

This is on ES 1.4.2

**Comment by dadoonet** [comment]
I just tested it on elasticsearch 1.4.2 and got:

```sh
$ bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.4.1
-> Installing elasticsearch/elasticsearch-cloud-aws/2.4.1...
Trying http://download.elasticsearch.org/elasticsearch/elasticsearch-cloud-aws/elasticsearch-cloud-aws-2.4.1.zip...
Downloading .........[skipped].....................DONE
Installed elasticsearch/elasticsearch-cloud-aws/2.4.1 into /Users/dpilato/Documents/Elasticsearch/apps/elasticsearch/elasticsearch-1.4.2/plugins/cloud-aws
```

**Comment by neonix888** [comment]
root@elk-prd:/usr/share/elasticsearch# bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.4.1
-> Installing elasticsearch/elasticsearch-cloud-aws/2.4.1...
Trying https://download.elastic.co/elasticsearch/elasticsearch-cloud-aws/elasticsearch-cloud-aws-2.4.1.zip ...
Downloading ...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................DONE
Verifying https://download.elastic.co/elasticsearch/elasticsearch-cloud-aws/elasticsearch-cloud-aws-2.4.1.zip checksums if available ...
NOTE: Unable to verify checksum for downloaded plugin (unable to find .sha1 or .md5 file to verify)
ERROR: Could not find plugin descriptor 'plugin-descriptor.properties' in plugin zip

**Comment by dadoonet** [comment]
Please read the very first lines of the README.

**Comment by neonix888** [comment]
@dadoonet , my bad and thank you
