### ISSUE TITLE
Snapshot S3Repository issue with eu-west-1 endpoint

### ISSUE THREAD

**Issue by malpani** [elasticsearch/elasticsearch-cloud-aws#171]
When region is null for snapshots, org.elasticsearch.repositories.s3.S3Repository tries to set the region as "EU" for eu-west-1 but the InternalS3AwsService does not recognize "EU" as a valid region

**Comment by ankon** [comment]
It seems that PR #169 is more logical here, as it avoids mixing well-known names of AWS with some newly introduced names like "EU"?

**Comment by malpani** [comment]
Either ways, considering InternalS3AwsService as a standalone library to access S3, guess it still makes sense to have this fix in place for completeness as EU is a valid region name - http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region

**Comment by dadoonet** [comment]
I agree with @ankon here and #169 will make it.

About region names vs. region ids, AWS plugin supports region ids actually. You can not set a region as `US West (Oregon)` AFAIK but as `us-west-2`. 
`EU` seems to be valid for `LocationConstraint` parameter we don't use.

Available names (ids) are:

* `us-east-1
* `us-west-2
* `us-west-1`
* `eu-west-1`
* `eu-central-1`
* `ap-southeast-1`
* `ap-southeast-2`
* `ap-northeast-1`
* `sa-east-1`
